name: Build Docker 

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # build test docker image (only on pull requests to save resources)
    - name: Set up QEMU
      if: success() 
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      if: success() 
      uses: docker/setup-buildx-action@v1        
    - name: Docker Buildx (build)
      if: success() 
      run: |
        sh scripts/docker_buildx.sh false
  
    # push to dockerhub
    - name: Login to DockerHub
      if: success() 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Buildx (push)
      if: success() 
      run: |
        sh scripts/docker_buildx.sh true  